### ISSUE TITLE
Планы на будущее (todo)

### ISSUE THREAD

**Issue by alexander-ii** [ruosm-presets/literan-moscow#81]
- [x] Не использовать `ru.text` и `ru.name` в аттрибутах, если перевод совпадает с тем, что в https://translations.launchpad.net/josm/trunk. Вроде бы в таком случае он подтягивается сам.
- [ ] Добавить `ref=` в учебные заведения
- [ ] Добавить `drink:` в сетевые заведения (просмотреть меню на их сайтах)
- [ ] Перетрясти группировку. Основные группы сильно не менять, но возможно создать новые группы или подгруппы. Или добавить сепаратор внутри групп.
- [ ] Перебросить иконки с ссылок на внешные ресурсы на гитхаб
(:small_red_triangle_down: выхлоп невелик :heavy_exclamation_mark: очень трудозатратно)
    - Скачать/нарисовать/раздобыть иконки 
    - Разместить их в этом репозитарии
    - Поменять ссылки в заготовках
    - Пожелания к иконкам:
        - квадратные
        - размером 16х16 (смотреть `icon_size` в https://josm.openstreetmap.de/wiki/TaggingPresets)
        - svg либо png, с прозрачным фоном
        - не нарушающие ничьи права и лицензии

**Comment by AntonKhorev** [comment]
Насчёт `ru.name`: нужно ли было придумывать английские названия тем заведениям, у которых их нет? У меня в josm английский интерфейс включен, потому что включена консоль, в которую я не хочу, чтобы козяблики писались. Зачем мне в меню видеть всякие "Moshoztorg"? Как это поможет тем, кто не умеет по-русски читать, если на месте всё равно по-русски написано?

**Comment by alexander-ii** [comment]
@AntonKhorev Стоит попробовать, как будет без них. Может и стоит их экстерминировать. На досуге попробую.  
Но с ними есть ленивый вариант через `F3` набирать на латинице и найти нужную заготовку, не переключая раскладки.

А логика, почему они появились, была в том, что дефолтный язык у заготовки — английский. И было лениво переделывать его на русский. Потому всему были даны названия на латинице. Но тут, да, может быть не применима.

**Comment by batyrmastyr** [comment]
Как насчёт перевода блока Healtcare 2.0 и добавления маникюрных салонов (shop=beauty + beauty=nails)?

**Comment by alexander-ii** [comment]
@batyrmastyr 
> Как насчёт перевода блока Healtcare 2.0

Я не против :)) Ждать pull request?
Они и в вики осм не переведены, туда тоже можно вписать.

>добавления маникюрных салонов (shop=beauty + beauty=nails)

А это лучше с @literannn обсудить. Он как раз за заготовки взялся, а у меня лапки всё больше и больше касательно ОСМ :(
Но возможно лучшим решением будет создать тикет/патч в трекере JOSM-а, чтобы это в дефолтную заготовку попало.

**Comment by literannn** [comment]
Насчет shop=beauty + beauty=nails: этот набор заготовок идеологически включает в себя конкретные сети (если нужно добавить какую-то сеть салонов красоты - не вопрос, но желательно, чтобы там хотя бы не меньше сотни заведений было). 

А если речь идет про то, чтобы только добавить выпадающий список со значениями тега beauty - то это оптимальнее в стандартную заготовку. Кстати, кто подскажет адрес их репы?

**Comment by batyrmastyr** [comment]
@literannn адрес репозитория найти [не сложно](https://josm.openstreetmap.de/browser/josm/trunk/resources/data/defaultpresets.xml). А вот сетей из сотни салонов не видел ни разу, правда и не искал.
@alexander-ii тогда лучше начать с Вики.
